site_name: Muhammad Suleman Khetran
nav:
  - Home: index.md
  - About: about.md
  - Experiance: experiance.md
  - Projects: projects.md
  - Academics: academics.md
  # - About: en/about.md
  # - Refrences: ServiceMode.md
  # - Logs: Logs.md

# \docs\assets\image\sk.png
# docs/assets/image/
theme: 
  name: material
  logo: assets/image/sk.png
  favicon: assets/image/sk.ico
  features:
    - navigation.tabs
    - search.suggest
    # - navigation.instant
    # - navigation.path
    # - navigation.indexes
    # - content.action.edit
    # - content.action.view
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    top: fontawesome/solid/angle-up
    menu: fontawesome/solid/angle-down
  palette:
    # primary: teal
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    # scheme: default
extra_css:
  - css/neoteroi-mkdocs.css
  - "extra.css"
  
plugins:
  - search
  - termynal
  # - glightbox:
  #     touchNavigation: true
  #     loop: false
  #     effect: zoom
  #     slide_effect: slide
  #     width: 100%
  #     height: auto
  #     zoomable: true
  #     draggable: true
  #     skip_classes:
  #       - custom-skip-class-name
  #     auto_caption: false
  #     caption_position: bottom

  # - i18n:
  #     docs_structure: suffix
  #     languages:
  #       - locale: en
  #         default: true
  #         name: English
  #         build: true
        # - locale: fr
        #   name: Français
        #   build: true
          # theme:
          #   palette:
          #     primary: red
          # nav_translations:
          #   Home: index.md
          #   Getting Started: Démarrage Rapide
          #   Plugins Compatibility: Compatibilité des plugins

markdown_extensions:
  - neoteroi.timeline
  - attr_list
  - md_in_html
  - toc

copyright: |
 &copy 2024 <a href="https://github.com/suleman-khetran" target="_blank" rel="noopener">Suleman Khetran</a>